In [ ]:
#In NumPy, arrays must have the same length to perform calculations.

In NumPy, arrays must have the same length to perform calculations.


In [1]:
import numpy as np

In [2]:
arr = np.array([
    [1,2,3,4],
    [10,2,3,4]
])

arr

array([[ 1,  2,  3,  4],
       [10,  2,  3,  4]])

In [14]:
arr.shape

(2, 4)

In [15]:
# size
arr.size

8

In [16]:
# ndim
arr.ndim

2

In [17]:
# dtype
arr.dtype

dtype('int64')

In [7]:
#arange
np.arange(1,15,4)

array([ 1,  5,  9, 13])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,100,5)
#In linspace, we pass the starting value, ending value, and the number of values we want evenly spaced.

array([  0.,  25.,  50.,  75., 100.])

In [19]:
new_arr = np.array([
    [2,4,5,10],
    [2,4,5,10],
    [2,4,5,10]
])
new_arr.sum()


63

In [20]:
new_arr.mean()

5.25

In [22]:
new_arr.max()

10

In [29]:
a1 = np.array([
    [1,8,4,10,3,2],
    [100,8,4,10,3,2]
])

a1.sort()
a1

array([[  1,   2,   3,   4,   8,  10],
       [  2,   3,   4,   8,  10, 100]])

In [31]:
a1.transpose()

array([[  1,   2],
       [  2,   3],
       [  3,   4],
       [  4,   8],
       [  8,  10],
       [ 10, 100]])

In [ ]:
array = np.array([1,2,4,7,9,3,77,3,4])
a = array.reshape(3,-1)
a[0][0] = 100
a

array([[100,   2,   4],
       [  7,   9,   3],
       [ 77,   3,   4]])

In [25]:
array

array([100,   2,   4,   7,   9,   3,  77,   3,   4])

In [13]:
d2_arr = np.array([
    [1,2,3],
    [2,6,8],
    [2,5,8]
])
newarr = d2_arr.flatten()

In [19]:
newarr[0] = 100
newarr
d2_arr

array([[1, 2, 3],
       [2, 6, 8],
       [2, 5, 8]])

In [28]:
arr = np.array([1,3,4,6,8,9,11,16,18,20])

a = arr[2:7].copy()
a[0] = 1000
a

array([1000,    6,    8,    9,   11])

In [29]:
arr

array([ 1,  3,  4,  6,  8,  9, 11, 16, 18, 20])